name-template: 'Version $NEXT_PATCH_VERSION - Summary Here🌈'
tag-template: '$NEXT_PATCH_VERSION'
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📝 Documentation'
    label: 'documentation'
  - title: '🌍 Translation'
    label: 'translation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  Thanks again to $CONTRIBUTORS! 🎉
no-changes-template: 'Changes are coming soon 😎'
replacers:
  - search: '/(?:and )?@dependabot(?:\[bot\])?,?/g'
    replace: ''
  - search: '/(?:and )?@sourcery-ai-bot(?:\[bot\])?,?/g'
    replace: ''
  - search: '/(?:and )?@allcontributors(?:\[bot\])?,?/g'
    replace: ''
  - search: ', !'
    replace: '!'
